### PR TITLE
More flexible LaTeX Creation Handling

### PR DESCRIPTION
**Pull request by CarliJoy**
I added the possibility to print the created pdf directly (under unix) instead of only delivering it to the users.

For this I needed to re-fracture the core.py and had to create a class from the run_tex function.

This make the pdf creation process more flexible and allows users easier modifications.

Tests and documentation was also added.

### CODE REVIEW

**Comment by CarliJoy** [comment]
I would be glad if you cloud merge this request and update the version on pypi accordingly.

**Comment by weinbusch** [comment]
Thanks for your contribution, CarliJoy. To be honest, I am not too keen on accepting the pr for the following reasons:

- Printing on a local printer is not a core function of `django-tex`. In fact, I think that is not even a core function of a web application. Instead of including printing in `django-tex`, there should be a wrapper that passes the output of `django-tex` (or the output of any other part of the web app) to the local printer. See below for a suggestion on how to do this.

-  As I am working on windows, I cannot test Linux printing commands and cannot test your pr.

- Instead of refactoring core.py to get access to the temporary pdf file, you might want to pass the file object returned by `run_tex` to a `subprocess` as explained here: [https://stackoverflow.com/a/12725233](https://stackoverflow.com/a/12725233)

**Comment by weinbusch** [comment]
I'll close this for now.

**Comment by CarliJoy** [comment]
weinbusch, thank you for pointing out directly passing the file object to lpr, really seems to be a more straight forward and simple solution also to me.

**Pull request closed without merging**
